server:
  port: 8090
logging:
  file: logs/dev_profile_app.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: DEBUG
    net.ivancl4udio.apps.oauth2server: DEBUG
spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:D:/dev/H2/DB/oauth2/oauth
    username: sa
    password: 123456
    driver-class-name: org.h2.Driver
